// Mocks generated by Mockito 5.0.15 from annotations
// in watchnow/test/presentation/bloc/get_episode_detail_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:watchnow/common/failure.dart' as _i6;
import 'package:watchnow/domain/entities/episode_detail.dart' as _i7;
import 'package:watchnow/domain/repositories/tv_show_repository.dart' as _i2;
import 'package:watchnow/domain/usecases/get_episode_detail.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeTVShowRepository_0 extends _i1.Fake implements _i2.TVShowRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetEpisodeDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEpisodeDetail extends _i1.Mock implements _i4.GetEpisodeDetail {
  MockGetEpisodeDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.EpisodeDetail>> execute(
          int? id, int? seasonNumber, int? episodeNumber) =>
      (super.noSuchMethod(
          Invocation.method(#execute, [id, seasonNumber, episodeNumber]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.EpisodeDetail>>.value(
              _FakeEither_1<_i6.Failure, _i7.EpisodeDetail>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.EpisodeDetail>>);

  @override
  String toString() => super.toString();
}
