// Mocks generated by Mockito 5.0.15 from annotations
// in watchnow/test/presentation/bloc/watchlist_tv_show_status_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:watchnow/common/failure.dart' as _i7;
import 'package:watchnow/domain/entities/tv_show_detail.dart' as _i8;
import 'package:watchnow/domain/repositories/tv_show_repository.dart' as _i2;
import 'package:watchnow/domain/usecases/get_watchlist_tv_show_status.dart'
    as _i4;
import 'package:watchnow/domain/usecases/remove_watchlist_tv_show.dart' as _i9;
import 'package:watchnow/domain/usecases/save_watchlist_tv_show.dart' as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeTVShowRepository_0 extends _i1.Fake implements _i2.TVShowRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetWatchListTVShowStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListTVShowStatus extends _i1.Mock
    implements _i4.GetWatchListTVShowStatus {
  MockGetWatchListTVShowStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);

  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);

  @override
  String toString() => super.toString();
}

/// A class which mocks [SaveWatchlistTVShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTVShow extends _i1.Mock
    implements _i6.SaveWatchlistTVShow {
  MockSaveWatchlistTVShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);

  @override
  _i5.Future<_i3.Either<_i7.Failure, String>> execute(
          _i8.TVShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShow]),
              returnValue: Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>()))
          as _i5.Future<_i3.Either<_i7.Failure, String>>);

  @override
  String toString() => super.toString();
}

/// A class which mocks [RemoveWatchlistTVShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTVShow extends _i1.Mock
    implements _i9.RemoveWatchlistTVShow {
  MockRemoveWatchlistTVShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);

  @override
  _i5.Future<_i3.Either<_i7.Failure, String>> execute(
          _i8.TVShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShow]),
              returnValue: Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>()))
          as _i5.Future<_i3.Either<_i7.Failure, String>>);

  @override
  String toString() => super.toString();
}
